import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:firebase_storage/firebase_storage.dart';
import 'package:squaad/Data.dart';

Future<UserData> generateUser({bool register=false}) async {
    String gender = Random.secure().nextBool()? 'male' : 'female';

  UserData userData = UserData("-"+generateId(27),
  name: gender == 'male'? _getRandomElement(_maleNames) : _getRandomElement(_femaleNames),
  bio: "I'm an autogenerated user. Registered: $register",
  location: _getRandomElement(_geoHashes));

  HttpClient client = HttpClient();
  HttpClientRequest request = await client.getUrl(Uri.parse("https://randomuser.me/api/?inc=picture&gender=$gender"));
  HttpClientResponse response = await request.close();
    if (response.statusCode != 200) throw Exception('Failed to fetch user gen: ${response.reasonPhrase}');
    else {
      String imgUrl = jsonDecode(utf8.decode(await response.single))['results'][0]['picture']['large'];
      request = await client.getUrl(Uri.parse(imgUrl));
      response = await request.close();
      if (response.statusCode != 200) throw Exception('Failed to fetch user gen: ${response.reasonPhrase}');
      else {
        List<int> bytes = List();
        bytes = await response.fold<List<int>>(bytes, (bytes, newData) => List.from(bytes)..addAll(newData));
        userData.photos.add(Uint8List.fromList(bytes));
      }
    }

  if (Random().nextInt(3) < 1) userData.likes.add(localUserData.docRef);

  if (register) {
    await userData.docRef.setData(<String, dynamic>{
      'uid' : userData.uid,
      'name': userData.name,
      'email' : userData.email,
      'bio': userData.bio,
      'location': userData.location,
      'loginTimestamp': userData.loginTimestamp,
      'groups': userData.groups,
      'likes': userData.likes
    });

    FirebaseStorage.instance.ref().child(userData.uid+'_0').putData(userData.photos.first);
  }

  print('Generated User Named ${userData.name}');
  return userData;
}

dynamic _getRandomElement(List list) {
  int randIndex = (Random.secure().nextDouble()*(list.length)).floor();
  return list.elementAt(randIndex);
}

String generateId(int length) => String.fromCharCodes(Iterable.generate(length, (index) => _uidPool.codeUnitAt((Random.secure().nextDouble()*(_uidPool.length)).floor())));
String _uidPool = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";

List<String> _geoHashes = ['dnkkd6', 'dnkh3m', 'djgzzx', 'dr5reg', 'gcpvj0'];

List<String> _femaleNames = ['Beverly','Tanya','Jaclyn','Frances','Heather',
'Susan','Monica','Juliet','Sara','Diana','Teresa','Bernice','Mary','Veronica',
'Phyllis','Billie','Staci','Velda','Lynn','Santa','Jennifer','Christina',
'Nelia','Jane','Ettie','Sha','Lindsey','Marian','Marie','Katherine','Ella',
'Andrea','Roseline','Mary','Mary','Ellen','Carmen','Elaine','Rosemary','Nora',
'Abby','Darlene','Kelly','Josephine','Cynthia','Melissa','Vilma','Helen',
'Angela','Marlene','Patricia','Marion','Peggie','Kathryn','Cristina','Clara',
'Rosemary','Tara','Frances','Bonnie','Priscilla','Lucy','Elisabeth','Jo',
'Tiffany','Cynthia','Dorthy','Sally','Trudy','Maria','Dominique','Sabrina',
'Amy','Cleta','Alice','Karen','Tracie','Shonda','Teisha','Diana','Cindy',
'Cheryl','Sherri','Martha','Kimberly','Gloria','Mattie','Linda','Barbara',
'Jean','Donna','Darlene','Judy','Sadie','Betty','Sheri','Diana','Frankie',
'Doreen','Hilary','Julie','Carol','Chantelle','Tammy','Elizabeth','Sara',
'Destiny','Paula','Gerda','Hannah','Dorothy','Anna','Janis','Raquel','Maxine',
'Edith','Erin','Whitley','Angelita','Irma','Delores','Johnnie','Lonnie',
'Jean','Teri','Cynthia','Sally','Tanya','Carole','Phyllis','Samantha',];

List<String> _maleNames = ['Jesus','Robert','Claude','Joseph','Raymond',
'Charles','Roy','Jonathan','Steven','Michael','Mitchell','Rodolfo','James',
'Edward','Justin','Joshua','Darren','Lorenzo','Eric','George','Leroy',
'Christopher','Justin','Jerry','Brian','Jesus','Anthony','Jay','Samuel',
'Anthony','Richard','Avery','Michael','Bobby','Gregory','Jeffrey','Ron',
'Antony','Robert','Richard','Henry','Hans','Robert','William','Terrance',
'Robert','Ralph','Frederick','David','Ted','Fred','Dale','Philip','Eduardo',
'Jeffrey','Michael','Jeremy','Daniel','Paul','Carroll','Orville','Jack',
'Thomas','Jeffrey','Joseph','Clyde','James','John','Joseph','Daniel','Robert',
'Marcus','Marc','Ronald','Michael','Russell','Omar','Ronald','Sang','George',
'Francis','Hector','Fletcher','Jeffrey','Royce','Robert','Jim','James',
'Jason','Edward','David','Anthony','Joe','Shawn','William','James','John',
'Miguel','Dale','Carl','Luke','August','Cameron','James','Thomas','James',
'Donald','William','Earl','Bobby','Jose','John','Martin','Phillip','William',
'Andrew','Joshua','Jerry','Randall'];